@host = http://localhost:5111
@token = replace-with-jwt

GET {{host}}/health
Accept: application/json
###

GET {{host}}/health/readiness
Accept: application/json

###

POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "admin@example.test",
  "password": "replace-with-admin-password"
}

###

GET {{host}}/api/reminders/dead-lettered
Authorization: Bearer {{token}}
Accept: application/json
